## Reading the file

In [2]:
import pandas as pd
df=pd.read_csv("StudentsPerformance.csv")

In [3]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df.shape

(1000, 8)

In [6]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [47]:
df['writing score'].median()

np.float64(69.0)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [16]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

## FOR FINDING ONLY NO OF ROWS

In [26]:
df.shape[0]

1000

FOR FINDING NULL VALUES

In [33]:
df.isnull().sum(axis=0)

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [40]:
df[["math score"]].mean()

math score    66.089
dtype: float64

In [44]:
df[['math score']].max()

math score    100
dtype: int64

FOR MEDIAN I M DOING MEANS 50% FROM DESCRIBE FUNCTION WILL GET THE VALUE

In [51]:
df['math score'].median()

np.float64(66.0)

In [68]:
df=pd.read_csv("StudentsPerformance.csv")

In [70]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

STORING TOTAL SCORE BY CREATING IT AND STORING EACH COLUMN MARKS INTO IT AND ADDING TO OUR datset

In [71]:
df["Total score"]=df['writing score']+df['reading score']+df['math score']
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229

In [75]:
df["Average score"]=df['Total score']/3
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score,Average score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [76]:
df['Total score'].head()

0    218
1    247
2    278
3    148
4    229
Name: Total score, dtype: int64

In [77]:
df['Average score'].head()

0    72.666667
1    82.333333
2    92.666667
3    49.333333
4    76.333333
Name: Average score, dtype: float64

FOR FINDING OUT THE MAX VALUE AT INDEX FROM THE CSV FILE

In [80]:
topper=df["Total score"].idxmax()
topper

458

FOR FINDING THE ROW FOR THE TOPPER AND OTHER INFORMATION loc → Label-based indexing

In [86]:
df.loc[topper]

gender                                    female
race/ethnicity                           group E
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                   100
reading score                                100
writing score                                100
Total score                                  300
Average score                              100.0
Name: 458, dtype: object

iloc:integer based location ; gives same output as loc but just it gives o/p according to the integer index

In [87]:
df.iloc[topper]

gender                                    female
race/ethnicity                           group E
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                   100
reading score                                100
writing score                                100
Total score                                  300
Average score                              100.0
Name: 458, dtype: object

In [91]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'Total score', 'Average score'],
      dtype='object')

In [95]:
df['Total score'].sort_values(ascending=False).head()

916    300
962    300
458    300
114    299
712    297
Name: Total score, dtype: int64

In [100]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'Total score', 'Average score'],
      dtype='object')

(Show failed students)

In [106]:
df[df['math score']<40]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score,Average score
9,female,group B,high school,free/reduced,none,38,60,50,148,49.333333
17,female,group B,some high school,free/reduced,none,18,32,28,78,26.000000
55,female,group C,high school,free/reduced,none,33,41,43,117,39.000000
59,female,group C,some high school,free/reduced,none,0,17,10,27,9.000000
61,male,group A,some high school,free/reduced,none,39,39,34,112,37.333333
69,female,group C,associate's degree,standard,none,39,64,57,160,53.333333
76,male,group E,some high school,standard,none,30,26,22,78,26.000000
91,male,group C,high school,free/reduced,none,27,34,36,97,32.333333
145,female,group C,some college,free/reduced,none,22,39,33,94,31.333333
211,male,group C,some college,free/reduced,none,35,28,27,90,30.000000
217,female,group C,high school,free/reduced,none,34,42,39,115,38.333333
284,female,group B,some high school,standard,none,37,46,46,129,43.000000
327,male,group A,some college,free/reduced,none,28,23,19,70,23.333333
338,female,group B,some high school,free/reduced,none,24,38,27,89,29.666667
339,female,group D,some high school,free/reduced,completed,35,55,60,150,50.000000
363,female,group D,some high school,free/reduced,none,27,34,32,93,31.000000
383,female,group E,some high school,free/reduced,none,38,49,45,132,44.000000
384,female,group A,some high school,free/reduced,none,38,43,43,124,41.333333
455,male,group C,bachelor's degree,free/reduced,none,37,56,47,140,46.666667
466,female,group D,associate's degree,free/reduced,none,26,31,38,95,31.666667
527,female,group C,high school,free/reduced,none,36,53,43,132,44.000000
528,female,group D,bachelor's degree,free/reduced,none,29,41,47,117,39.000000
555,female,group C,some college,free/reduced,none,32,39,33,104,34.666667
596,male,group B,high school,free/reduced,none,30,24,15,69,23.000000
601,female,group C,high school,standard,none,29,29,30,88,29.333333
616,female,group E,bachelor's degree,standard,none,37,45,38,120,40.000000
620,female,group C,high school,free/reduced,none,35,61,54,150,50.000000
683,female,group C,some high school,free/reduced,completed,29,40,44,113,37.666667
741,female,group A,associate's degree,free/reduced,none,37,57,56,150,50.000000
777,female,group C,some college,free/reduced,none,35,44,43,122,40.666667
785,female,group B,some high school,standard,completed,32,51,44,127,42.333333
787,female,group B,some college,standard,none,19,38,32,89,29.666667
840,female,group D,high school,free/reduced,none,39,52,46,137,45.666667
842,female,group B,high school,free/reduced,completed,23,44,36,103,34.333333
862,male,group D,bachelor's degree,free/reduced,completed,39,42,38,119,39.666667
895,female,group E,some high school,free/reduced,none,32,34,38,104,34.666667
896,male,group B,high school,free/reduced,none,36,29,27,92,30.666667
902,female,group A,high school,free/reduced,completed,34,48,41,123,41.000000
921,female,group C,high school,free/reduced,none,35,53,46,134,44.666667
980,female,group B,high school,free/reduced,none,8,24,23,55,18.333333

Count failed students

In [107]:
df[df['math score']<40].shape[0]

40

In [108]:
df[df['reading score']<40].shape[0]

26